"""Self-contained management consoles shipped with Hub and Node hosts."""

from __future__ import annotations

import html


_STYLE = """
:root{color-scheme:light;--bg:#f4f0e8;--panel:#fffdf8;--ink:#23211d;--muted:#746f66;
--line:#ddd6c9;--brand:#476b5c;--brand2:#dfe9e3;--danger:#a3483d}*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif}
main{width:min(880px,calc(100% - 32px));margin:36px auto 80px}.hero{display:flex;gap:16px;align-items:center;margin-bottom:22px}
.node-console main{width:min(1080px,calc(100% - 32px))}.console-tabs{position:sticky;top:0;z-index:10;display:flex;gap:7px;overflow:auto;margin:0 0 16px;padding:8px;background:#f4f0e8e8;backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}
.console-tabs button{flex:0 0 auto;margin:0;background:transparent;color:var(--muted);padding:9px 13px}.console-tabs button.active{background:var(--brand);color:white}.console-panel.hidden{display:none!important}
.actionbar{position:sticky;top:67px;z-index:9;display:flex;align-items:center;gap:9px;flex-wrap:wrap;margin-bottom:16px;padding:11px 14px;background:#fffdf8ed;border:1px solid var(--line);border-radius:14px;backdrop-filter:blur(12px);box-shadow:0 8px 24px #4d45340d}.actionbar .status{flex:1 1 320px;margin:0}.actionbar button{margin:0}
.mark{width:54px;height:54px;border-radius:17px;background:var(--brand);color:white;display:grid;place-items:center;font-size:24px;font-weight:800}
h1,h2,p{margin:0}h1{font-size:27px}h2{font-size:18px;margin-bottom:12px}.lead,.muted{color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 8px 24px #4d45340d}
.card h3{margin:0 0 5px}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}.section-head p{max-width:680px}.button-row{display:flex;gap:8px;flex-wrap:wrap}.button-row button{margin-top:10px}.danger{background:#f7e3df!important;color:var(--danger)!important}details.card>summary,details.advanced>summary{cursor:pointer;font-weight:700;color:var(--brand)}details.advanced{margin-top:16px;padding-top:12px;border-top:1px solid var(--line)}
.workflow{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin-top:12px}.workflow span{padding:6px 10px;border-radius:999px;background:var(--brand2);color:var(--brand);font-size:13px;font-weight:700}.workflow b{color:var(--muted)}.field-status{min-height:22px;margin-top:7px;color:var(--muted);font-size:13px}.subsection{margin-top:16px}.subsection-title{margin:0 0 10px;font-size:16px}.busy{opacity:.6;pointer-events:none}
label{display:block;color:var(--muted);font-size:13px;margin:12px 0 5px}input,select,textarea{width:100%;border:1px solid var(--line);border-radius:11px;background:white;color:var(--ink);padding:11px 12px;font:inherit}
input[type=checkbox]{width:auto;transform:scale(1.15);margin-right:8px}.check{display:flex;align-items:center;color:var(--ink);font-size:14px}.compact{min-height:96px}
textarea{min-height:170px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;resize:vertical}
button{border:0;border-radius:11px;background:var(--brand);color:white;padding:11px 15px;font:600 14px inherit;cursor:pointer;margin-top:14px}button.secondary{background:var(--brand2);color:var(--brand)}button:disabled{opacity:.45;cursor:not-allowed}
.status{margin-top:14px;padding:11px 12px;border-radius:11px;background:var(--brand2);color:var(--brand);white-space:pre-wrap}.error{background:#f7e3df;color:var(--danger)}
.hidden{display:none!important}.nodes{display:grid;gap:9px;margin-top:12px}.node{display:flex;justify-content:space-between;gap:12px;padding:11px;border:1px solid var(--line);border-radius:12px}.online{color:var(--brand);font-weight:700}.offline{color:var(--muted)}
.steps{padding-left:20px;color:var(--muted)}code{background:#ece6db;padding:2px 5px;border-radius:5px}img.qr{display:block;width:min(320px,100%);margin:16px auto;border:12px solid white;border-radius:14px}
"""


def _lifecycle_card(role: str) -> str:
    return f"""<section class="card" style="margin-top:16px"><h2>本机产品管理</h2><p class="muted">管理这台电脑上的 Hub / Node 服务和签名产品更新。停用角色保留数据，Windows 与 Linux 使用同一流程。</p><div id="lifecycleStatus" class="status">正在读取…</div><button id="lifecycleRefresh" class="secondary">刷新</button><button data-life="restart" data-role="{role}">重启当前服务</button><button data-life="activate" data-role="hub" class="secondary">启用 Hub</button><button data-life="deactivate" data-role="hub" class="secondary">停用 Hub</button><button data-life="activate" data-role="node" class="secondary">启用 Node</button><button data-life="deactivate" data-role="node" class="secondary">停用 Node</button><button data-life="rollback" class="secondary">回退上一版本</button><label>签名 Knoa 产品 Bundle（.zip）</label><input id="bundleFile" type="file" accept=".zip"><button id="updateButton">安装更新</button><div id="lifecycleAction" class="status hidden"></div></section>"""


def _node_configuration_card() -> str:
    return """
<div id="configActions" class="actionbar hidden">
  <div id="configStatus" class="status">正在加载 Node 配置…</div>
  <button id="reloadConfig" class="secondary">重新加载当前配置</button>
  <button id="publishConfig" class="secondary">发布高级 JSON 更改</button>
</div>
<section class="console-panel hidden" data-console-panel="models">
  <section class="card">
    <h2>LLM 配置</h2><p class="muted">先连接 Provider，再声明它提供的 Model，最后到 Agent 页面选择模型。常规按钮都会直接校验、发布并热生效，不需要再提交一次草稿。</p>
    <div class="workflow"><span>1 Provider 连接</span><b>→</b><span>2 Model</span><b>→</b><span>3 Agent 使用</span><b>→</b><span>4 按需共享</span></div>
  </section>
  <h3 class="subsection-title subsection">1. Provider 连接</h3>
  <div class="grid">
    <section class="card">
      <div class="section-head"><div><h2>编辑已有 Provider</h2><p class="muted">Endpoint 和 API Key 只保存在本 Node。Workspace 远程 Provider 由“共享”页面管理。</p></div></div>
      <label>Provider</label><select id="providerSelect"></select>
      <label>类型</label><select id="providerDriver"><option value="llamacpp">llama.cpp（本机）</option><option value="openai">OpenAI</option><option value="openai_compatible">OpenAI Compatible</option><option value="anthropic">Anthropic</option><option value="workspace_remote">Workspace 远程模型</option></select>
      <label>Server URL / API Base</label><input id="providerEndpoint" placeholder="http://127.0.0.1:8080">
      <label class="check"><input id="providerRequiresKey" type="checkbox">调用时需要 API Key</label>
      <label>API Key 引用</label><input id="providerKeyRef" placeholder="openai_company_key">
      <label>更新 API Key（留空则保持不变）</label><input id="secretValue" type="password" autocomplete="new-password">
      <div id="providerSecretStatus" class="field-status"></div>
      <div class="button-row"><button id="applyProvider">保存并热生效</button><button id="deleteProvider" class="danger">删除 Provider</button></div>
    </section>
    <section class="card">
      <h2>新增 Provider</h2><p class="muted">一次填写完整连接。保存成功后立即出现在 Model 的 Provider 列表中。</p>
      <label>Provider ID</label><input id="newProviderId" placeholder="openai_company">
      <label>类型</label><select id="newProviderDriver"><option value="llamacpp">llama.cpp（本机）</option><option value="openai">OpenAI</option><option value="openai_compatible" selected>OpenAI Compatible</option><option value="anthropic">Anthropic</option></select>
      <label>Server URL / API Base</label><input id="newProviderEndpoint" placeholder="https://api.example.com/v1">
      <label class="check"><input id="newProviderRequiresKey" type="checkbox" checked>调用时需要 API Key</label>
      <label>API Key（可稍后补充）</label><input id="newProviderSecret" type="password" autocomplete="new-password">
      <button id="addProvider">新增并热生效</button>
    </section>
  </div>
  <h3 class="subsection-title subsection">2. Model</h3>
  <div class="grid">
    <section class="card">
      <div class="section-head"><div><h2>编辑已有 Model</h2><p class="muted">Model 是 Agent 选择的稳定别名，实际请求由所选 Provider 发出。</p></div></div>
      <label>当前 Model</label><select id="modelSelect"></select>
      <label>连接 Provider</label><select id="modelProvider"></select>
      <label>Provider 中的模型名称</label><input id="modelName">
      <label class="check"><input id="modelVision" type="checkbox">支持图片输入</label>
      <div class="button-row"><button id="applyModel">保存并热生效</button><button id="makeDefaultModel" class="secondary">设为默认模型</button><button id="makeVisionModel" class="secondary">设为图片理解模型</button><button id="deleteModel" class="danger">删除 Model</button></div>
    </section>
    <section class="card">
      <h2>新增 Model</h2><p class="muted">一个 Provider 可以提供多个 Model；Alias 是本 Node 内供 Agent 选择的稳定名称。</p>
      <label>Model Alias</label><input id="newModelAlias" placeholder="qwen_vision">
      <label>使用 Provider</label><select id="newModelProvider"></select>
      <label>Provider 中的模型名称</label><input id="newModelName" placeholder="qwen3.5-4b">
      <label class="check"><input id="newModelVision" type="checkbox">支持图片输入</label>
      <button id="addModel">新增并热生效</button>
    </section>
  </div>
</section>
<section class="console-panel hidden" data-console-panel="agents">
  <div class="grid">
    <section class="card">
      <div class="section-head"><div><h2>Agent</h2><p class="muted">选择 Agent 使用的模型，并管理是否启用、是否作为默认入口。</p></div></div>
      <label>当前 Agent</label><select id="agentSelect"></select>
      <label>显示名称</label><input id="agentDisplayName">
      <label>Agent 使用模型</label><select id="agentModel"></select>
      <label class="check"><input id="agentEnabled" type="checkbox">启用 Agent</label>
      <div class="button-row"><button id="makeDefaultAgent" class="secondary">设为默认 Agent</button><button id="applyAgent">保存并热生效</button></div>
    </section>
    <section class="card">
      <h2>新增自定义 Agent</h2><p class="muted">内置 knoa、reviewer_agent、codex 由产品提供；自定义 Agent 从 knoa 的安全默认值创建。</p>
      <label>Agent ID</label><input id="newAgentId" placeholder="research_agent">
      <div class="button-row"><button id="addAgent">新建并热生效</button><button id="deleteAgent" class="danger">删除当前自定义 Agent</button></div>
    </section>
  </div>
  <section class="card" style="margin-top:16px">
    <h2>角色 Prompt</h2><label>Prompt</label><textarea id="agentInstructions" class="compact"></textarea><label>内置 Prompt 引用（与 Prompt 二选一）</label><input id="agentInstructionsRef">
    <details class="advanced"><summary>调用方式、Tools 与 Subagent 高级策略</summary><div class="grid"><div><label>调用方式</label><select id="agentVisibility"><option value="user">用户直接使用</option><option value="delegate">仅作为 Subagent</option><option value="system">系统服务专用</option></select><label>允许的 Platform Tool（逗号分隔）</label><input id="agentTools" placeholder="* 或 read_file, web_search"><label>Capability ceiling（逗号分隔）</label><input id="agentCapabilities" placeholder="* 或 host_read, network"></div><div><label class="check"><input id="delegationAllowed" type="checkbox">允许创建受治理 Child Task</label><label>Subagent 目标 ID（逗号分隔）</label><input id="delegationTargets" placeholder="codex, research_agent"><label>最大深度</label><input id="delegationDepth" type="number" min="0" max="8"><label>Child 总数 / 并行数</label><div style="display:flex;gap:8px"><input id="delegationChildren" type="number" min="0" max="32"><input id="delegationParallel" type="number" min="0" max="32"></div><label>Child 超时（秒）</label><input id="delegationDeadline" type="number" min="0" max="86400"></div></div></details>
  </section>
</section>
<section class="console-panel hidden" data-console-panel="sharing">
  <div class="grid">
    <section class="card"><h2>共享本 Node 的模型</h2><p class="muted">共享页独立选择模型；只授权确实需要调用它的 Node，不会复制 Endpoint 或 API Key。</p><label>要共享的 Model</label><select id="shareModelSelect"></select><div id="shareModelDetail" class="field-status"></div><label class="check"><input id="shareEnabled" type="checkbox">共享所选 Model 到 Workspace</label><label>远程并发上限</label><input id="shareConcurrency" type="number" min="1" max="64" value="1"><div id="shareNodes" class="nodes"><span class="muted">正在读取 Workspace Node…</span></div><button id="applyShare">保存并热生效</button></section>
    <section class="card"><div class="section-head"><div><h2>其他 Node 授权给我的模型</h2><p class="muted">添加后会成为本 Node 的远程 Model，可再绑定给本地 Agent。</p></div><button id="reloadWorkspace" class="secondary">刷新</button></div><div id="remoteModels" class="nodes"><span class="muted">正在读取共享目录…</span></div></section>
  </div>
</section>
<section class="console-panel hidden" data-console-panel="system">
  <details class="card"><summary>高级完整配置 JSON</summary><p class="muted" style="margin-top:8px">仅用于审计和紧急维护。日常配置请使用模型、Agent 与共享页面。</p><textarea id="configDocument" style="min-height:420px"></textarea></details>
</section>"""


def hub_console_html(csrf_token: str, public_url: str) -> str:
    csrf = html.escape(csrf_token, quote=True)
    public_hub = html.escape(public_url, quote=True)
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Knoa Hub Console</title><style>{_STYLE}</style></head><body><main>
<div class="hero"><div class="mark">K</div><div><h1>Knoa Hub Console</h1><p class="lead">管理帐号、Workspace、Node Enrollment 与本机 Hub 生命周期</p></div></div>
<div class="grid"><section class="card" id="loginCard"><h2>登录 Hub</h2><label>登录帐号</label><input id="login" autocomplete="username"><label>密码</label><input id="password" type="password" autocomplete="current-password"><button id="loginButton">登录</button><div id="loginStatus" class="status hidden"></div></section>
<section class="card hidden" id="workspaceCard"><h2>当前 Workspace</h2><label>Workspace</label><select id="workspace"></select><button id="selectButton">打开 Workspace</button><button id="logoutButton" class="secondary">退出登录</button><div id="workspaceStatus" class="status hidden"></div></section></div>
<section class="card hidden" id="nodeCard" style="margin-top:16px"><h2>添加 Node</h2><ol class="steps"><li>在这里生成一次性 Enrollment Code。</li><li>在目标电脑打开本地 Node Console：<code>http://127.0.0.1:9531/console</code>。</li><li>粘贴 Code 并点击“加入 Workspace”。</li></ol><button id="grantButton">生成 Enrollment Code</button><button id="copyButton" class="secondary hidden">复制 Code</button><textarea id="grant" class="hidden" readonly></textarea><div id="grantStatus" class="status hidden"></div><div class="nodes" id="nodes"></div></section>
{_lifecycle_card("hub")}
</main><script>
let token="", selected=null, timer=null;const csrf="{csrf}",publicHub="{public_hub}";
const el=id=>document.getElementById(id); const show=(id,on=true)=>el(id).classList.toggle("hidden",!on);
function status(id,text,bad=false){{const box=el(id);box.textContent=text;box.classList.toggle("error",bad);show(id,true)}}
async function api(path,options={{}}){{const headers={{"Content-Type":"application/json",...(options.headers||{{}})}};if(token)headers.Authorization=`Bearer ${{token}}`;const response=await fetch(path,{{...options,headers}});const body=await response.json().catch(()=>({{}}));if(!response.ok)throw new Error(body.error||`HTTP ${{response.status}}`);return body}}
el("loginButton").onclick=async()=>{{try{{status("loginStatus","正在登录…");const body=await api("/v1/hosted/sessions",{{method:"POST",body:JSON.stringify({{login_identity:el("login").value.trim(),password:el("password").value}})}});token=body.access_token;el("password").value="";el("workspace").innerHTML=body.workspaces.map(w=>`<option value="${{w.workspace_id}}">${{w.display_name}} · ${{w.kind}}</option>`).join("");el("workspace").dataset.items=JSON.stringify(body.workspaces);show("loginCard",false);show("workspaceCard");status("workspaceStatus",`已登录：${{body.display_name}}`);}}catch(e){{status("loginStatus",`登录失败：${{e.message}}`,true)}}}};
el("selectButton").onclick=async()=>{{const items=JSON.parse(el("workspace").dataset.items||"[]");selected=items.find(w=>w.workspace_id===el("workspace").value);if(!selected)return;show("nodeCard");status("workspaceStatus",`已选择：${{selected.display_name}}`);await refreshNodes();clearInterval(timer);timer=setInterval(refreshNodes,5000)}};
el("logoutButton").onclick=async()=>{{try{{await api("/v1/hosted/session",{{method:"DELETE"}})}}catch(_){{}}token="";selected=null;clearInterval(timer);show("workspaceCard",false);show("nodeCard",false);show("loginCard")}};
el("grantButton").onclick=async()=>{{if(!selected)return;try{{status("grantStatus","正在生成…");const base=selected.workspace_path;const [hub,grant]=await Promise.all([api(`${{base}}/v1/hub`),api(`${{base}}/v1/node-enrollment-grants`,{{method:"POST",body:JSON.stringify({{ttl_seconds:600}})}})]);const payload={{version:"knoa-node-enrollment-v1",hub_url:publicHub+base,hub_id:hub.hub_id,hub_signing_public_key:hub.signing_public_key,grant_id:grant.grant_id,grant_secret:grant.secret,challenge:grant.challenge,expires_at:grant.expires_at}};el("grant").value=JSON.stringify(payload);show("grant");show("copyButton");status("grantStatus","Code 10 分钟内有效，只能使用一次。")}}catch(e){{status("grantStatus",`生成失败：${{e.message}}`,true)}}}};
el("copyButton").onclick=async()=>{{await navigator.clipboard.writeText(el("grant").value);status("grantStatus","已复制。现在到目标电脑的 Node Console 粘贴。")}};
async function refreshNodes(){{if(!selected)return;try{{const body=await api(`${{selected.workspace_path}}/v1/nodes`);el("nodes").innerHTML=body.nodes.length?body.nodes.map(n=>`<div class="node"><span><strong>${{n.display_name}}</strong><br><span class="muted">${{n.platform}} · ${{n.node_id}}</span></span><span class="${{n.online?'online':'offline'}}">${{n.online?'在线':'离线'}}</span></div>`).join(""):"<p class='muted'>当前 Workspace 还没有 Node。</p>"}}catch(e){{status("grantStatus",`Node 状态加载失败：${{e.message}}`,true)}}}}
async function life(path,options={{}}){{const response=await fetch(path,{{...options,headers:{{"X-Knoa-Console":csrf,...(options.headers||{{}})}}}});const body=await response.json().catch(()=>({{}}));if(!response.ok)throw new Error(body.error||`HTTP ${{response.status}}`);return body}}
function renderLife(body){{el("lifecycleStatus").textContent=`平台：${{body.platform}} / ${{body.architecture}}\n版本：${{body.current_release||'未安装'}}\nHub：${{body.services.hub.active?'运行中':'已停止'}}\nNode：${{body.services.node.active?'运行中':'已停止'}}`}}
async function refreshLife(){{try{{renderLife(await life("/v1/console/lifecycle"))}}catch(e){{status("lifecycleStatus",`生命周期服务不可用：${{e.message}}`,true)}}}}
async function lifeAction(action,role=null,bundle_name=null){{try{{status("lifecycleAction","正在执行，请稍候…");const body=await life("/v1/console/lifecycle/actions",{{method:"POST",headers:{{"Content-Type":"application/json"}},body:JSON.stringify({{action,role,bundle_name}})}});renderLife(body);status("lifecycleAction","操作完成。")}}catch(e){{status("lifecycleAction",`操作已提交或失败：${{e.message}}`,true);setTimeout(refreshLife,4000)}}}}
el("lifecycleRefresh").onclick=refreshLife;document.querySelectorAll("[data-life]").forEach(button=>button.onclick=()=>lifeAction(button.dataset.life,button.dataset.role||null));
el("updateButton").onclick=async()=>{{const file=el("bundleFile").files[0];if(!file)return status("lifecycleAction","请选择 .zip Bundle。",true);try{{status("lifecycleAction","正在上传签名 Bundle…");const uploaded=await life(`/v1/console/lifecycle/bundles/${{encodeURIComponent(file.name)}}`,{{method:"PUT",headers:{{"Content-Type":"application/zip"}},body:file}});await lifeAction("update",null,uploaded.bundle_name)}}catch(e){{status("lifecycleAction",`更新失败：${{e.message}}`,true)}}}};
refreshLife();
</script></body></html>"""


def node_console_html(csrf_token: str) -> str:
    token = html.escape(csrf_token, quote=True)
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Knoa Node Console</title><style>{_STYLE}</style></head><body class="node-console"><main>
<div class="hero"><div class="mark">N</div><div><h1>Knoa Node Console</h1><p class="lead">管理这台电脑的模型、Agent、Workspace 共享和运行状态</p></div></div>
<nav class="console-tabs" aria-label="Node Console 导航"><button class="active" data-console-tab="overview">概览</button><button data-console-tab="models">LLM 配置</button><button data-console-tab="agents">Agent</button><button data-console-tab="sharing">共享</button><button data-console-tab="system">系统</button></nav>
<section class="console-panel" data-console-panel="overview"><div class="grid"><section class="card" id="enrollmentCard"><h2>连接 Workspace Hub</h2><p class="muted">仅首次安装或更换 Workspace 时需要。</p><label>Hub Console 生成的 Enrollment Code</label><textarea id="payload" placeholder='{{"version":"knoa-node-enrollment-v1", ...}}'></textarea><label>Node 显示名称</label><input id="displayName" value="Windows Desktop"><button id="enrollButton">加入 Workspace</button><div id="enrollStatus" class="status hidden"></div></section>
<section class="card"><h2>Node 状态与 App</h2><div id="status" class="status">正在读取…</div><div class="button-row"><button id="refreshButton" class="secondary">刷新状态</button><button id="pairButton">生成 App 配对二维码</button></div><img id="qr" class="qr hidden" alt="App pairing QR"><div id="pairStatus" class="status hidden"></div></section></div></section>
{_node_configuration_card()}
<div class="console-panel hidden" data-console-panel="system">{_lifecycle_card("node")}</div>
</main><script>
const csrf="{token}";const el=id=>document.getElementById(id);const show=(id,on=true)=>el(id).classList.toggle("hidden",!on);function note(id,text,bad=false){{const box=el(id);box.textContent=text;box.classList.toggle("error",bad);show(id)}}
const configurableTabs=new Set(["models","agents","sharing","system"]);function openConsoleTab(name){{if(!["overview","models","agents","sharing","system"].includes(name))name="overview";document.querySelectorAll("[data-console-tab]").forEach(button=>button.classList.toggle("active",button.dataset.consoleTab===name));document.querySelectorAll("[data-console-panel]").forEach(panel=>panel.classList.toggle("hidden",panel.dataset.consolePanel!==name));show("configActions",configurableTabs.has(name));history.replaceState(null,"",`#${{name}}`)}}document.querySelectorAll("[data-console-tab]").forEach(button=>button.onclick=()=>openConsoleTab(button.dataset.consoleTab));openConsoleTab(location.hash.slice(1)||"overview");
function apiError(body,status){{const issue=body?.validation?.issues?.[0];if(issue)return `${{issue.message}}${{issue.path?` (${{issue.path}})`:""}}`;if(body?.detail)return `${{body.detail}}${{body.path?` (${{body.path}})`:""}}`;return body?.error||`HTTP ${{status}}`}}
async function localApi(path,options={{}}){{const response=await fetch(path,{{...options,headers:{{"Content-Type":"application/json","X-Knoa-Console":csrf,...(options.headers||{{}})}}}});const type=response.headers.get("content-type")||"";if(!response.ok){{const body=type.includes("json")?await response.json():{{}};throw new Error(apiError(body,response.status))}}return type.includes("json")?response.json():response.blob()}}
async function refresh(){{try{{const body=await localApi("/v1/console/status");const hub=body.hub;show("enrollmentCard",!hub.enrolled);el("status").textContent=hub.enrolled?`运行正常\nNode：${{body.node.display_name||body.node.node_id}}\n运行版本：${{body.runtime_version}}\nWorkspace Hub：${{hub.hub.hub_url}}\n远程连接：${{hub.relay_connected?'在线（优先尝试 P2P）':'正在连接'}}`:`尚未加入 Workspace\n运行版本：${{body.runtime_version}}\n请使用左侧 Enrollment Code 完成连接。`;el("status").classList.remove("error")}}catch(e){{note("status",`状态读取失败：${{e.message}}`,true)}}}}
el("refreshButton").onclick=refresh;
el("enrollButton").onclick=async()=>{{try{{let payload=JSON.parse(el("payload").value.trim());if(payload.version!=="knoa-node-enrollment-v1")throw new Error("Enrollment Code 类型不正确");delete payload.version;delete payload.expires_at;payload.display_name=el("displayName").value.trim()||"Knoa Node";note("enrollStatus","正在加入 Workspace…");await localApi("/v1/console/hub/enroll",{{method:"POST",body:JSON.stringify(payload)}});el("payload").value="";note("enrollStatus","Enrollment 成功，Relay 正在连接。返回 Hub Console 即可看到 Node。");await refresh()}}catch(e){{note("enrollStatus",`Enrollment 失败：${{e.message}}`,true)}}}};
el("pairButton").onclick=async()=>{{try{{note("pairStatus","正在生成二维码…");const blob=await localApi("/v1/console/pairing",{{method:"POST",body:"{{}}"}});if(el("qr").src)URL.revokeObjectURL(el("qr").src);el("qr").src=URL.createObjectURL(blob);show("qr");note("pairStatus","请在 App 的当前 Workspace 中点击“配对 App”并扫描。二维码 5 分钟有效。")}}catch(e){{note("pairStatus",`生成失败：${{e.message}}`,true)}}}};
let configDoc=null,workspaceState=null,publishing=false;const builtInAgents=new Set(["knoa","reviewer_agent","codex"]),idPattern=/^[A-Za-z][A-Za-z0-9_.-]{{0,127}}$/,secretPattern=/^[a-z][a-z0-9_.-]{{0,127}}$/;const csv=value=>[...new Set(value.split(",").map(item=>item.trim()).filter(Boolean))];function options(target,values){{target.innerHTML=values.map(value=>`<option value="${{value}}">${{value}}</option>`).join("")}}
async function stableId(prefix,value){{const bytes=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return `${{prefix}}_${{[...new Uint8Array(bytes)].map(v=>v.toString(16).padStart(2,"0")).join("").slice(0,40)}}`}}
function syncConfigForm(selectedAgent="",selectedProvider="",selectedModel=""){{if(!configDoc)return;const providers=Object.keys(configDoc.providers),localProviders=providers.filter(id=>configDoc.providers[id].driver!=="workspace_remote"),models=Object.keys(configDoc.models),agents=Object.keys(configDoc.agents.agents),previousShare=el("shareModelSelect").value;options(el("providerSelect"),providers);options(el("modelProvider"),providers);options(el("newModelProvider"),localProviders.length?localProviders:providers);options(el("modelSelect"),models);options(el("shareModelSelect"),models);options(el("agentModel"),models);options(el("agentSelect"),agents);if(previousShare&&models.includes(previousShare))el("shareModelSelect").value=previousShare;if(selectedProvider&&providers.includes(selectedProvider))el("providerSelect").value=selectedProvider;if(selectedModel&&models.includes(selectedModel))el("modelSelect").value=selectedModel;if(selectedAgent&&agents.includes(selectedAgent))el("agentSelect").value=selectedAgent;void loadProvider();loadModel();loadAgent();renderSharing()}}
async function loadProvider(){{if(!configDoc)return;const provider=configDoc.providers[el("providerSelect").value];if(!provider)return;const remote=provider.driver==="workspace_remote";el("providerDriver").value=provider.driver;el("providerEndpoint").value=provider.server_url||provider.api_base||"";el("providerRequiresKey").checked=provider.requires_api_key??["openai","openai_compatible","anthropic"].includes(provider.driver);el("providerKeyRef").value=provider.api_key_ref||"";el("secretValue").value="";["providerDriver","providerEndpoint","providerRequiresKey","providerKeyRef","secretValue","applyProvider"].forEach(id=>el(id).disabled=remote);el("providerSecretStatus").textContent=remote?"远程 Provider 的连接由源 Node 管理。":"正在读取 Secret 状态…";if(!remote&&provider.api_key_ref){{try{{const state=await localApi(`/v1/console/secrets/${{encodeURIComponent(provider.api_key_ref)}}`);el("providerSecretStatus").textContent=state.configured?`API Key 已配置 · 指纹 ${{state.fingerprint||"已保护"}}`:"API Key 尚未配置"}}catch(e){{el("providerSecretStatus").textContent=`Secret 状态读取失败：${{e.message}}`}}}}else if(!remote)el("providerSecretStatus").textContent="此 Provider 未绑定 API Key 引用。"}}
function loadModel(){{if(!configDoc)return;const alias=el("modelSelect").value,model=configDoc.models[alias];if(model){{el("modelProvider").value=model.provider;el("modelName").value=model.model;el("modelVision").checked=Boolean(model.supports_vision);el("makeDefaultModel").disabled=alias===configDoc.default_model;el("makeVisionModel").disabled=!model.supports_vision||alias===configDoc.vision_model;el("makeVisionModel").textContent=alias===configDoc.vision_model?"已是图片理解模型":"设为图片理解模型"}}}}
function loadAgent(){{if(!configDoc)return;const agentId=el("agentSelect").value,agent=configDoc.agents.agents[agentId];if(!agent)return;el("agentDisplayName").value=agent.display_name;el("agentVisibility").value=agent.visibility;el("agentVisibility").disabled=agent.visibility==="system"||agentId===configDoc.agents.default_agent;el("agentEnabled").checked=agent.enabled;el("agentEnabled").disabled=agentId===configDoc.agents.default_agent;el("agentModel").disabled=agent.model_binding.ownership!=="platform";if(agent.model_binding.ownership==="platform")el("agentModel").value=agent.model_binding.model;el("agentInstructions").value=agent.instructions||"";el("agentInstructions").placeholder=agent.instructions_ref||"自定义 Prompt";el("agentInstructionsRef").value=agent.instructions_ref||"";el("agentTools").value=(agent.allowed_platform_tools||[]).join(", ");el("agentCapabilities").value=(agent.platform_capability_ceiling||[]).join(", ");el("delegationAllowed").checked=agent.delegation.allowed;el("delegationTargets").value=(agent.delegation.targets||[]).join(", ");el("delegationDepth").value=agent.delegation.max_depth;el("delegationChildren").value=agent.delegation.max_children;el("delegationParallel").value=agent.delegation.max_parallel_children;el("delegationDeadline").value=agent.delegation.max_deadline_seconds;el("makeDefaultAgent").disabled=agentId===configDoc.agents.default_agent||agent.visibility!=="user";el("deleteAgent").disabled=builtInAgents.has(agentId)||agentId===configDoc.agents.default_agent}}
function updateEditor(){{el("configDocument").value=JSON.stringify(configDoc,null,2)}}
function providerEndpoint(driver){{return driver==="llamacpp"?"http://127.0.0.1:8080":driver==="openai"?"https://api.openai.com/v1":driver==="anthropic"?"https://api.anthropic.com":""}}
function setNewProviderDefaults(){{const driver=el("newProviderDriver").value,current=el("newProviderEndpoint").value.trim(),presets=["http://127.0.0.1:8080","https://api.openai.com/v1","https://api.anthropic.com"];if(!current||presets.includes(current))el("newProviderEndpoint").value=providerEndpoint(driver);el("newProviderRequiresKey").checked=driver!=="llamacpp"}}
async function writeSecret(reference,value){{if(!value)return null;if(!reference)throw new Error("需要 API Key 时必须设置 API Key 引用");return localApi(`/v1/console/secrets/${{encodeURIComponent(reference)}}`,{{method:"PUT",body:JSON.stringify({{value}})}})}}
async function publishCurrent(summary,success){{if(publishing)return false;publishing=true;document.body.classList.add("busy");updateEditor();try{{note("configStatus","正在校验并热发布…");const body=await localApi("/v1/console/config/publish",{{method:"POST",body:JSON.stringify({{document:configDoc,summary}})}});if(body.result?.state?.apply_status==="failed")throw new Error(body.result.state.apply_error_code||"配置应用失败");const syncError=body.workspace_sync?.error?`；Workspace 共享同步待重试：${{body.workspace_sync.error}}`:"";await loadConfig(`${{success}} · 已热生效${{syncError}}`);return true}}catch(e){{note("configStatus",`保存失败：${{e.message}}`,true);return false}}finally{{publishing=false;document.body.classList.remove("busy")}}}}
async function loadConfig(success=""){{try{{if(!success)note("configStatus","正在加载…");const body=await localApi("/v1/console/config");configDoc=body.revision.document;updateEditor();syncConfigForm();await loadWorkspace();note("configStatus",success||`已应用版本 ${{body.state.applied_revision_id}} · ${{body.state.apply_status}}`)}}catch(e){{note("configStatus",`配置加载失败：${{e.message}}`,true)}}}}
async function loadWorkspace(){{try{{workspaceState=await localApi("/v1/console/workspace-resources");renderSharing()}}catch(e){{workspaceState=null;el("shareNodes").innerHTML=`<span class="muted">共享控制面不可用：${{e.message}}</span>`;el("remoteModels").innerHTML='<span class="muted">共享目录暂不可用</span>'}}}}
function renderSharing(){{if(!configDoc)return;const alias=el("shareModelSelect").value,model=configDoc.models[alias],entry=Object.entries(configDoc.model_deployments||{{}}).find(([,item])=>item.model_alias===alias),deployment=entry?.[1];el("shareModelDetail").textContent=model?`${{model.model||alias}} · ${{model.supports_vision?'支持图片':'文本模型'}}`:"请选择 Model";el("shareEnabled").checked=Boolean(deployment?.share_enabled);el("shareConcurrency").value=deployment?.max_remote_concurrency||1;const allowed=new Set(deployment?.allowed_node_ids||[]);if(!workspaceState)return;const peers=workspaceState.nodes.filter(node=>node.node_id!==workspaceState.node_id);el("shareNodes").innerHTML=peers.length?peers.map(node=>`<label class="check"><input type="checkbox" data-share-node="${{node.node_id}}" ${{allowed.has(node.node_id)?'checked':''}}>${{node.display_name}} · ${{node.online?'在线':'离线'}}</label>`).join(""):'<span class="muted">Workspace 中没有其他 Node</span>';const remotes=workspaceState.deployments.filter(item=>item.target_node_id!==workspaceState.node_id&&item.enabled);el("remoteModels").innerHTML=remotes.length?remotes.map(item=>{{const resource=workspaceState.resources.find(value=>value.resource_id===item.resource_id),source=workspaceState.nodes.find(value=>value.node_id===item.target_node_id),attached=Object.values(configDoc.providers).some(value=>value.driver==="workspace_remote"&&value.remote_deployment_id===item.deployment_id);return `<div class="node"><span><strong>${{resource?.display_name||item.deployment_id}}</strong><br><span class="muted">${{source?.display_name||item.target_node_id}} · ${{attached?'已添加':'可调用'}}</span></span><button class="secondary" data-attach-model="${{item.deployment_id}}" ${{attached?'disabled':''}}>添加</button></div>`}}).join(""):'<span class="muted">当前没有授权给本 Node 的共享模型</span>';document.querySelectorAll("[data-attach-model]").forEach(button=>button.onclick=()=>attachRemoteModel(button.dataset.attachModel))}}
el("providerSelect").onchange=()=>void loadProvider();el("modelSelect").onchange=loadModel;el("shareModelSelect").onchange=renderSharing;el("agentSelect").onchange=loadAgent;el("newProviderDriver").onchange=setNewProviderDefaults;
el("applyProvider").onclick=async()=>{{const id=el("providerSelect").value,provider=configDoc.providers[id],driver=el("providerDriver").value,endpoint=el("providerEndpoint").value.trim(),required=el("providerRequiresKey").checked,keyRef=el("providerKeyRef").value.trim(),secret=el("secretValue").value;if(!provider||driver==="workspace_remote")return note("configStatus","Workspace 远程 Provider 请在共享页面管理。",true);if(!endpoint)return note("configStatus","请填写 Provider Endpoint。",true);if((required||["openai","anthropic"].includes(driver))&&!keyRef)return note("configStatus","这个 Provider 需要 API Key 引用。",true);if(keyRef&&!secretPattern.test(keyRef))return note("configStatus","API Key 引用必须使用小写安全标识。",true);provider.driver=driver;provider.server_url=driver==="llamacpp"?endpoint:"";provider.api_base=driver!=="llamacpp"?endpoint:"";provider.api_key_ref=keyRef;provider.api_key_env="";provider.requires_api_key=required;try{{const state=await writeSecret(keyRef,secret);if(state)provider.secret_version=(provider.secret_version||0)+1;await publishCurrent(`Update Provider ${{id}}`,`Provider ${{id}} 已保存`)}}catch(e){{note("configStatus",`保存失败：${{e.message}}`,true)}}}};
el("addProvider").onclick=async()=>{{const id=el("newProviderId").value.trim().toLowerCase(),driver=el("newProviderDriver").value,endpoint=el("newProviderEndpoint").value.trim(),required=el("newProviderRequiresKey").checked,secret=el("newProviderSecret").value;if(!secretPattern.test(id))return note("configStatus","Provider ID 必须以小写字母开头，只能包含小写字母、数字、_、. 和 -。",true);if(configDoc.providers[id])return note("configStatus","Provider 已存在。",true);if(!endpoint)return note("configStatus","请填写 Provider Endpoint。",true);const needsRef=required||["openai","anthropic"].includes(driver)||Boolean(secret),keyRef=needsRef?`${{id}}_key`:"";try{{const state=await writeSecret(keyRef,secret);configDoc.providers[id]={{driver,server_url:driver==="llamacpp"?endpoint:"",api_base:driver!=="llamacpp"?endpoint:"",api_key_ref:keyRef,api_key_env:"",remote_deployment_id:"",direct_gateway_url:"",secret_version:state?1:0,requires_api_key:required,timeout_seconds:120}};const saved=await publishCurrent(`Add Provider ${{id}}`,`Provider ${{id}} 已新增`);if(saved){{el("newProviderId").value="";el("newProviderSecret").value="";syncConfigForm("",id)}}}}catch(e){{note("configStatus",`保存失败：${{e.message}}`,true)}}}};
el("deleteProvider").onclick=async()=>{{const id=el("providerSelect").value,used=Object.entries(configDoc.models).filter(([,model])=>model.provider===id).map(([alias])=>alias);if(configDoc.providers[id]?.driver==="workspace_remote")return note("configStatus","请从共享模型关系中移除远程 Provider。",true);if(used.length)return note("configStatus",`Provider 仍被 Model 引用：${{used.join(", ")}}`,true);delete configDoc.providers[id];await publishCurrent(`Delete Provider ${{id}}`,`Provider ${{id}} 已删除`)}};
el("applyModel").onclick=async()=>{{const alias=el("modelSelect").value,model=configDoc.models[alias],name=el("modelName").value.trim();if(!name)return note("configStatus","请填写 Provider 中的模型名称。",true);model.provider=el("modelProvider").value;model.model=name;model.supports_vision=el("modelVision").checked;await publishCurrent(`Update Model ${{alias}}`,`Model ${{alias}} 已保存`)}};
el("addModel").onclick=async()=>{{const alias=el("newModelAlias").value.trim(),provider=el("newModelProvider").value,name=el("newModelName").value.trim();if(!idPattern.test(alias))return note("configStatus","Model Alias 格式无效。",true);if(configDoc.models[alias])return note("configStatus","Model Alias 已存在。",true);if(!provider||!name)return note("configStatus","请选择 Provider 并填写其中的模型名称。",true);configDoc.models[alias]={{provider,model:name,supports_vision:el("newModelVision").checked,context_window:null,thinking:null}};const saved=await publishCurrent(`Add Model ${{alias}}`,`Model ${{alias}} 已新增`);if(saved){{el("newModelAlias").value="";el("newModelName").value="";el("newModelVision").checked=false;syncConfigForm("",provider,alias)}}}};
el("makeDefaultModel").onclick=async()=>{{const alias=el("modelSelect").value;configDoc.default_model=alias;await publishCurrent(`Set default Model ${{alias}}`,`默认模型已设为 ${{alias}}`)}};
el("makeVisionModel").onclick=async()=>{{const alias=el("modelSelect").value;if(!configDoc.models[alias]?.supports_vision)return note("configStatus","图片理解模型必须启用图片输入。",true);configDoc.vision_model=alias;await publishCurrent(`Set Vision Model ${{alias}}`,`图片理解模型已设为 ${{alias}}`)}};
el("deleteModel").onclick=async()=>{{const alias=el("modelSelect").value;if(alias===configDoc.default_model)return note("configStatus","默认模型不能删除，请先切换默认模型。",true);if(alias===configDoc.vision_model)return note("configStatus","图片理解模型不能删除，请先选择其他图片理解模型。",true);if(alias===configDoc.fallback_model)return note("configStatus","Fallback 模型不能删除，请先清除 Fallback。",true);const agents=Object.entries(configDoc.agents.agents).filter(([,agent])=>agent.model_binding.ownership==="platform"&&agent.model_binding.model===alias).map(([id])=>id);if(agents.length)return note("configStatus",`Model 仍被 Agent 引用：${{agents.join(", ")}}`,true);const deployments=Object.entries(configDoc.model_deployments||{{}}).filter(([,item])=>item.model_alias===alias).map(([id])=>id);if(deployments.length)return note("configStatus","请先关闭并删除这个 Model 的共享 Deployment。",true);delete configDoc.models[alias];await publishCurrent(`Delete Model ${{alias}}`,`Model ${{alias}} 已删除`)}};
el("applyShare").onclick=async()=>{{const alias=el("shareModelSelect").value,enabled=el("shareEnabled").checked,allowed=[...document.querySelectorAll("[data-share-node]:checked")].map(item=>item.dataset.shareNode),existing=Object.entries(configDoc.model_deployments||{{}}).find(([,item])=>item.model_alias===alias);if(!alias||!configDoc.models[alias])return note("configStatus","请先选择要共享的 Model。",true);if(!workspaceState)return note("configStatus","Workspace 控制面当前不可用。",true);let deploymentId=existing?.[0];if(!deploymentId)deploymentId=await stableId("model_deployment",`${{workspaceState.node_id}}:${{alias}}`);const resourceId=existing?.[1].resource_id||await stableId("model_resource",`${{workspaceState.node_id}}:${{alias}}`);configDoc.model_deployments[deploymentId]={{model_alias:alias,resource_id:resourceId,display_name:configDoc.models[alias].model||alias,enabled:true,share_enabled:enabled,max_remote_concurrency:Math.max(1,Math.min(64,Number(el("shareConcurrency").value)||1)),allowed_node_ids:enabled?allowed:[]}};await publishCurrent(`Update Model sharing ${{alias}}`,`${{alias}} 共享授权已保存`)}};
async function attachRemoteModel(deploymentId){{const deployment=workspaceState.deployments.find(item=>item.deployment_id===deploymentId),resource=workspaceState.resources.find(item=>item.resource_id===deployment.resource_id),digest=(await stableId("remote",deploymentId)).slice(7),providerId=`remote_provider_${{digest}}`,alias=`remote_model_${{digest}}`;configDoc.providers[providerId]={{driver:"workspace_remote",server_url:"",api_base:"",api_key_ref:"",api_key_env:"",remote_deployment_id:deploymentId,direct_gateway_url:"",secret_version:0,requires_api_key:false,timeout_seconds:600}};configDoc.models[alias]={{provider:providerId,model:resource?.spec?.model_identity||resource?.display_name||deploymentId,supports_vision:Boolean(resource?.spec?.declared_capabilities?.vision),context_window:null,thinking:null}};await publishCurrent(`Attach remote Model ${{deploymentId}}`,`${{resource?.display_name||alias}} 已添加为远程 Model`)}}
el("applyAgent").onclick=async()=>{{const agentId=el("agentSelect").value,agent=configDoc.agents.agents[agentId],instructions=el("agentInstructions").value.trim(),instructionsRef=el("agentInstructionsRef").value.trim();if(Boolean(instructions)===Boolean(instructionsRef))return note("configStatus","Prompt 与内置 Prompt 引用必须且只能填写一个。",true);agent.display_name=el("agentDisplayName").value.trim();agent.visibility=el("agentVisibility").value;agent.enabled=el("agentEnabled").checked;if(agent.model_binding.ownership==="platform")agent.model_binding.model=el("agentModel").value;agent.instructions=instructions;agent.instructions_ref=instructionsRef;agent.allowed_platform_tools=csv(el("agentTools").value);agent.platform_capability_ceiling=csv(el("agentCapabilities").value);const allowed=el("delegationAllowed").checked;if(allowed){{const children=Math.max(1,Number(el("delegationChildren").value)||1);agent.delegation={{allowed:true,targets:csv(el("delegationTargets").value),max_depth:Math.max(1,Number(el("delegationDepth").value)||1),max_children:children,max_parallel_children:Math.min(children,Math.max(1,Number(el("delegationParallel").value)||1)),max_deadline_seconds:Math.max(1,Number(el("delegationDeadline").value)||1800)}}}}else{{agent.delegation={{allowed:false,targets:[],max_depth:0,max_children:0,max_parallel_children:0,max_deadline_seconds:0}}}}if(agent.visibility!=="delegate")Object.values(configDoc.agents.agents).forEach(parent=>{{parent.delegation.targets=(parent.delegation.targets||[]).filter(target=>target!==agentId)}});await publishCurrent(`Update Agent ${{agentId}}`,`Agent ${{agentId}} 已保存`)}};
el("makeDefaultAgent").onclick=async()=>{{const agentId=el("agentSelect").value,agent=configDoc.agents.agents[agentId];if(agent.visibility!=="user")return note("configStatus","默认 Agent 必须允许用户直接使用。",true);agent.enabled=true;configDoc.agents.default_agent=agentId;await publishCurrent(`Set default Agent ${{agentId}}`,`默认 Agent 已设为 ${{agentId}}`)}};
el("addAgent").onclick=async()=>{{const agentId=el("newAgentId").value.trim().toLowerCase();if(!/^[a-z][a-z0-9_-]{{0,63}}$/.test(agentId))return note("configStatus","Agent ID 必须以小写字母开头，只能包含小写字母、数字、_ 和 -。",true);if(configDoc.agents.agents[agentId])return note("configStatus","这个 Agent ID 已存在。",true);const base=configDoc.agents.agents.knoa;if(!base)return note("configStatus","内置 Knoa Agent 不存在，无法创建自定义 Agent。",true);const agent=JSON.parse(JSON.stringify(base));agent.kind="knoa";agent.display_name=agentId;agent.instructions=`You are ${{agentId}}. Follow the user's objective and configured policies.`;agent.instructions_ref="";agent.visibility="user";agent.enabled=true;agent.model_binding={{ownership:"platform",model:configDoc.default_model,hint:""}};agent.max_concurrency=1;agent.default_skill_refs=[];agent.allowed_skill_refs=[];agent.allowed_platform_tools=["*"];agent.platform_capability_ceiling=["*"];agent.native_capability_ceiling=[];agent.runtime_limits={{max_iterations:null,max_output_tokens:null}};agent.delegation={{allowed:false,targets:[],max_depth:0,max_children:0,max_parallel_children:0,max_deadline_seconds:0}};agent.callable_by=[];agent.command=[];agent.home="";agent.cwd="";agent.sandbox="read-only";agent.approval_policy="never";configDoc.agents.agents[agentId]=agent;const saved=await publishCurrent(`Add Agent ${{agentId}}`,`Agent ${{agentId}} 已创建`);if(saved)el("newAgentId").value=""}};
el("deleteAgent").onclick=async()=>{{const agentId=el("agentSelect").value;if(builtInAgents.has(agentId))return note("configStatus","内置 Agent 不能删除，只能停用。",true);if(agentId===configDoc.agents.default_agent)return note("configStatus","请先切换默认 Agent。",true);delete configDoc.agents.agents[agentId];Object.values(configDoc.agents.agents).forEach(agent=>{{agent.delegation.targets=(agent.delegation.targets||[]).filter(target=>target!==agentId)}});await publishCurrent(`Delete Agent ${{agentId}}`,`Agent ${{agentId}} 已删除，历史工作记录保留`)}};
el("reloadWorkspace").onclick=loadWorkspace;el("reloadConfig").onclick=()=>loadConfig();el("publishConfig").onclick=async()=>{{try{{configDoc=JSON.parse(el("configDocument").value);await publishCurrent("Advanced Node Console JSON update","高级 JSON 配置已发布")}}catch(e){{note("configStatus",`JSON 无效：${{e.message}}`,true)}}}};setNewProviderDefaults();
function renderLife(body){{el("lifecycleStatus").textContent=`平台：${{body.platform}} / ${{body.architecture}}\n版本：${{body.current_release||'未安装'}}\nHub：${{body.services.hub.active?'运行中':'已停止'}}\nNode：${{body.services.node.active?'运行中':'已停止'}}`}}
async function refreshLife(){{try{{renderLife(await localApi("/v1/console/lifecycle"))}}catch(e){{note("lifecycleStatus",`生命周期服务不可用：${{e.message}}`,true)}}}}
async function lifeAction(action,role=null,bundle_name=null){{try{{note("lifecycleAction","正在执行，请稍候…");const body=await localApi("/v1/console/lifecycle/actions",{{method:"POST",body:JSON.stringify({{action,role,bundle_name}})}});renderLife(body);note("lifecycleAction","操作完成。")}}catch(e){{note("lifecycleAction",`操作已提交或失败：${{e.message}}`,true);setTimeout(refreshLife,4000)}}}}
el("lifecycleRefresh").onclick=refreshLife;document.querySelectorAll("[data-life]").forEach(button=>button.onclick=()=>lifeAction(button.dataset.life,button.dataset.role||null));
el("updateButton").onclick=async()=>{{const file=el("bundleFile").files[0];if(!file)return note("lifecycleAction","请选择 .zip Bundle。",true);try{{note("lifecycleAction","正在上传签名 Bundle…");const response=await fetch(`/v1/console/lifecycle/bundles/${{encodeURIComponent(file.name)}}`,{{method:"PUT",headers:{{"Content-Type":"application/zip","X-Knoa-Console":csrf}},body:file}});const uploaded=await response.json();if(!response.ok)throw new Error(uploaded.error||`HTTP ${{response.status}}`);await lifeAction("update",null,uploaded.bundle_name)}}catch(e){{note("lifecycleAction",`更新失败：${{e.message}}`,true)}}}};
refresh();setInterval(refresh,5000);
loadConfig();
refreshLife();
</script></body></html>"""


__all__ = ["hub_console_html", "node_console_html"]
