import { Stack, useFocusEffect, useLocalSearchParams } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

import { AppIcon } from "@/components/AppIcon";
import { AppPressable } from "@/components/AppPressable";
import { addHostedWorkspaceMember, listHostedWorkspaceMembers, listHostedWorkspaces, removeHostedWorkspaceMember, type HostedWorkspaceMember } from "@/hub/hubClient";
import { colors } from "@/theme";

export default function WorkspaceMembersScreen() {
  const params = useLocalSearchParams<{ workspaceId: string }>();
  const workspaceId = Array.isArray(params.workspaceId) ? params.workspaceId[0] ?? "" : params.workspaceId ?? "";
  const [members, setMembers] = useState<HostedWorkspaceMember[]>([]);
  const [login, setLogin] = useState("");
  const [loading, setLoading] = useState(true);
  const [working, setWorking] = useState("");
  const [error, setError] = useState("");
  const [canManage, setCanManage] = useState(false);
  const refresh = useCallback(async () => { setLoading(true); setError(""); try { const workspaces = await listHostedWorkspaces(); const workspace = workspaces.find((item) => item.workspaceId === workspaceId); setCanManage(Boolean(workspace?.kind === "shared" && workspace.role !== "member")); setMembers(await listHostedWorkspaceMembers(workspaceId)); } catch (caught) { setError(caught instanceof Error ? caught.message : "成员加载失败"); } finally { setLoading(false); } }, [workspaceId]);
  useFocusEffect(useCallback(() => { void refresh(); }, [refresh]));
  async function add() { if (!login.trim()) return; setWorking("add"); try { await addHostedWorkspaceMember(workspaceId, login.trim(), "member"); setLogin(""); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "成员添加失败"); } finally { setWorking(""); } }
  function remove(member: HostedWorkspaceMember) { Alert.alert("移除成员", `确认从 Workspace 移除 ${member.displayName || member.loginIdentity}？`, [{ text: "取消", style: "cancel" }, { text: "移除", style: "destructive", onPress: () => void (async () => { setWorking(member.accountId); try { await removeHostedWorkspaceMember(workspaceId, member.accountId); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "成员移除失败"); } finally { setWorking(""); } })() }]); }
  return <><Stack.Screen options={{ title: "成员与权限" }} /><ScrollView contentContainerStyle={styles.container}><View style={styles.header}><View style={styles.icon}><AppIcon name="user" color={colors.accent} size={26} /></View><View style={styles.flex}><Text style={styles.title}>Workspace 成员</Text><Text style={styles.meta}>成员可以访问 Workspace 控制面；Node 和共享资源仍分别需要配对与显式授权。</Text></View></View>{canManage ? <View style={styles.card}><Text style={styles.sectionTitle}>添加成员</Text><TextInput value={login} onChangeText={setLogin} placeholder="成员登录帐号" placeholderTextColor={colors.muted} autoCapitalize="none" style={styles.input} /><AppPressable disabled={working === "add"} style={styles.primary} onPress={() => void add()}>{working === "add" ? <ActivityIndicator color={colors.white} /> : <Text style={styles.primaryText}>添加成员</Text>}</AppPressable></View> : !loading ? <View style={styles.card}><Text style={styles.sectionTitle}>成员管理</Text><Text style={styles.meta}>个人 Workspace 只有所有者；共享 Workspace 的所有者或管理员可以添加成员。</Text></View> : null}{loading ? <ActivityIndicator color={colors.accent} /> : null}{members.map((member) => <View key={member.accountId} style={styles.card}><View style={styles.row}><View style={styles.flex}><Text style={styles.memberName}>{member.displayName || member.loginIdentity}</Text><Text style={styles.meta}>{member.loginIdentity} · {member.role}</Text></View>{canManage && member.role !== "owner" ? <AppPressable disabled={Boolean(working)} onPress={() => remove(member)}><Text style={styles.remove}>移除</Text></AppPressable> : <Text style={styles.owner}>{member.role === "owner" ? "所有者" : "成员"}</Text>}</View></View>)}{error ? <Text style={styles.error}>{error}</Text> : null}</ScrollView></>;
}
const styles = StyleSheet.create({ container: { padding: 17, gap: 13, paddingBottom: 52 }, header: { flexDirection: "row", alignItems: "center", gap: 12, padding: 16, borderRadius: 18, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, icon: { width: 48, height: 48, borderRadius: 15, alignItems: "center", justifyContent: "center", backgroundColor: colors.accentSoft }, flex: { flex: 1, minWidth: 0 }, title: { color: colors.ink, fontSize: 19, fontWeight: "800" }, meta: { color: colors.muted, fontSize: 12, lineHeight: 18 }, card: { padding: 15, gap: 11, borderRadius: 17, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, sectionTitle: { color: colors.ink, fontSize: 17, fontWeight: "800" }, input: { minHeight: 46, borderRadius: 12, borderWidth: 1, borderColor: colors.line, color: colors.ink, paddingHorizontal: 12 }, primary: { minHeight: 46, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: colors.accent }, primaryText: { color: colors.white, fontWeight: "800" }, row: { flexDirection: "row", alignItems: "center", gap: 12 }, memberName: { color: colors.ink, fontSize: 16, fontWeight: "800" }, remove: { color: colors.danger, fontWeight: "800" }, owner: { color: colors.accent, fontSize: 12, fontWeight: "800" }, error: { color: colors.danger, lineHeight: 20 } });
